name: otp_wrap
description: A customizable one-time-password (OTP) input field for Flutter. Supports paste, SMS autofill, obscured input, error states, and full styling control.
version: 0.0.2
repository: https://github.com/sanjay-cheemeni/otp_wrap
issue_tracker: https://github.com/sanjay-cheemeni/otp_wrap/issues

topics:
  - otp
  - input
  - widget
  - authentication

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0